### ISSUE TITLE
BPM loaded incorrectly - e.g. 1.2815E+16

### ISSUE THREAD

**Issue by FelixFifi** [xyonico/BeatSaberSongLoader#18]
Version:
Beat Saber v0.11.1
Song Loader 4.2

How to reproduce:
1. Download [Waiting for love - Avicii](https://bsaber.com/songs/2213/)
2. Play the song
3. All notes skip you or run into you at the very beginning

![image](https://user-images.githubusercontent.com/26076283/43028255-22c658aa-8c7f-11e8-8cac-b1872488def6.png)

Possible cause:
BPM is set to a float
`"_beatsPerMinute":128.14999389648438,`

**Comment by FelixFifi** [comment]
The value seems to be off by the factor 10^14 while the digits are the same as in the _json_ file.

**Comment by xyonico** [comment]
This has been fixed with this commit https://github.com/xyonico/BeatSaberSongLoader/commit/7af0d1f4419defb5f3fa13d8baea349b99c084c0

The problem was I wasn't stating a specific culture when converting the text to number, so for some system languages a decimal is separated with commas instead of periods.

I'll close this issue when the release is out.

**Comment by xyonico** [comment]
This is been fixed with this release:
https://github.com/xyonico/BeatSaberSongLoader/releases/tag/v4.2.2

**Comment by FelixFifi** [comment]
Thank you 👍 
I know that problem from my .NET projects :/

PS: Sorry for the duplicate issue 🙈
